name: League Analysis Container Build-Push Workflow

on:
  push: 
    branches: 
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t league-analysis-image:"${{ env.COMMIT_HASH }}" .

      - name: Tag Docker image
        run: |
          docker tag league-analysis-image:"${{ env.COMMIT_HASH }}" aryanbhatla/league-analysis-image:"${{ env.COMMIT_HASH }}"

      - name: Push Docker image
        run: |
          docker push aryanbhatla/league-analysis-image:${{ env.COMMIT_HASH }}
  

    